#+title: The Elements of Bioinformatics

* Programming
** SSH
*** Use ssh-key to access remote server easily.    
Besides using ~ssh username@address~ and then enter your password to
access remote server, you can use ssh-key to directly access it by
typing like ~ssh name~ without password and address. Here are the
references: [[https://www.ssh.com/academy/ssh/keygen][generating SSH-key]] and
[[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Github SSH-key]].

a. Generate public and private SSH key pair.
#+BEGIN_SRC bash
  # use -t to specify the algorithm for generating the key
  # use -f to specify the filename for the key pair, optinal.
  ssh-keygen -t ed25519 -f ~/.ssh/my_key
#+END_SRC
This will generate two files under ~/.ssh. One is the private key
stored in your local computer and do not share it with others. The
other is the public key named as ~/.ssh/my_key.pub. The public key
should be copied to your remote server.

b. Copy the public SSH key to remote server
#+BEGIN_SRC bash
  ssh-copy-id -i ~/.ssh/my_key username@address
#+END_SRC
This needs you to enter your password. And once it's done, you can
then access server by ~ssh username@address~ without password any
more.

c. Config the _your_home_directory/.ssh/config_ file.
Now we can step further to let ssh remember our address by editing the
SSH configuration file right under ~/.ssh/config. If you don't have
this file, simply create it by ~vim ~/.ssh/config~
#+BEGIN_SRC ssh
  Host user
    HostName xxx.xxx.xx.xx
    User username
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/my_key
#+END_SRC
Now you can access the server by simply using ~ssh user~.

** Make
   GNU make uses a _Makefile_ to control a work pipeline. Here a work
   pipeline is multiple tasks with dependencies, and the dependencies
   are inferred by ~make~ through the file (or output) dependencies.
   For example, task A generates ~a.output~, and task B uses
   ~a.output~ to generate ~b.output~, then we say task B depends on
   task A. We can use Makefile, a config file, to express this.

#+BEGIN_SRC make
  b.output : a.output
  [TAB]echo "Generate b.output" 
  [TAB]cat a.output > b.output
  a.output :
  [TAB]echo "Generate a.output"
  [TAB]touch a.output
#+END_SRC
  You can save the lines above into a file like /Makefile/. Then run
  ~make~. The system will generate both /a.output/ and /b.output/, if
  no such files exist before.
  
  1. By default, make will search /Makefile/ or /makefile/ under
     current path. You can use ~make -f /your_make_file/~ to let run
     whatever Makefile you named.
  2. If /a.output/ exists, then ~make~ will run the rule under
     ~b.output : a.output~, i.e., ~echo "Generate b.output"~ and
     ~cat a.output > b.output~
     
** Snakemake
   [[https://snakemake.readthedocs.io/en/stable/][Snakemake]] is Snake [Python] + make. It's widely used for complex
   pipeline management in bioinformatics.
   a. It's a job manager:
   - Handle jobs' dependencies like what make does.
   - Monitor the status of tasks.
   b. Compared with make, it has the advantages below:
   - Its syntax is more like a Python script, so very convenient to
     use.
   - It supports resource limitation, such as # of CPUs, size of RAM
     and so on.
   - It supports environment control, such as conda.
   - It supports the usages under HPC, such as slurm and PBS system.
   
*** Installation
    #+BEGIN_SRC shell
      # Use conda/mamba install ~snakemake~.
      mamba install -c conda-forge -c bioconda -c nodefaults snakemake
      # You can also use pip to install snakemake, please check the document.
    #+END_SRC 
    
*** A typical Snakemake script
#+BEGIN_SRC snakemake
   ## optional config file
   configfile: "config.yaml"
                
   content = "say hi"
   samples = ["a", "b"]
   ## all the output files you want to have
   rule all:
       input:
          expand("flag/pre_{s}.done", s = samples)
          expand("flag/first_{s}.done", s = samples)

   ## then set up the rules about how to generate them
   rule pre:
       output:
          # s will be infered based on rule all output
          # here it will be a or b.
          # snakemake will run s=a and s=b in parallel if possible
          # touch will be automatically  generate the flag file
          # once the rule is done.
          touch("flag/pre_{s}.done")
       log:
          "log/{s}.log"
       shell:
          """
          # wildcards.s to get the a / b
          echo "pre:" {content} {wildcards.s} 2> {log}
          """
  rule first:
      # snakemake will know that it depends on the output of pre
      # then the rule will run after pre
      input:
          "flag/pre_{s}.done"
      output:
          touch("flag/first_{s}.done")
      log:
          "log/{s}.log"
      shell:
          """
          echo "first:" {content} {wildcards.s} 2> {log}
          """
#+END_SRC
Use ~snakemake --snakefile demo.snakefile~ to run the above one
(saved as /demo.snakefile/).

   
