#+title: The Elements of Bioinformatics

* Programming

** SSH
*** Use ssh-key to access remote server easily.    
Besides using ~ssh username@address~ and then enter your password to
access remote server, you can use ssh-key to directly access it by
typing like ~ssh name~ without password and address. Here are the
references: [[https://www.ssh.com/academy/ssh/keygen][generating SSH-key]] and
[[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][Github SSH-key]].

a. Generate public and private SSH key pair.
#+BEGIN_SRC bash
  # use -t to specify the algorithm for generating the key
  # use -f to specify the filename for the key pair, optinal.
  ssh-keygen -t ed25519 -f ~/.ssh/my_key
#+END_SRC
This will generate two files under ~/.ssh. One is the private key
stored in your local computer and do not share it with others. The
other is the public key named as ~/.ssh/my_key.pub. The public key
should be copied to your remote server.

b. Copy the public SSH key to remote server
#+BEGIN_SRC bash
  ssh-copy-id -i ~/.ssh/my_key username@address
#+END_SRC
This needs you to enter your password. And once it's done, you can
then access server by ~ssh username@address~ without password any
more.

c. Config the _your_home_directory/.ssh/config_ file.
Now we can step further to let ssh remember our address by editing the
SSH configuration file right under ~/.ssh/config. If you don't have
this file, simply create it by ~vim ~/.ssh/config~
#+BEGIN_SRC ssh
  Host user
    HostName xxx.xxx.xx.xx
    User username
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/my_key
#+END_SRC
Now you can access the server by simply using ~ssh user~.

** Makefile
   GNU make uses a _Makefile_ to control a work pipeline. Here a work
   pipeline is multiple tasks with dependencies, and the dependencies
   are inferred by ~make~ through the file (or output) dependencies.
   For example, task A generates ~a.output~, and task B uses
   ~a.output~ to generate ~b.output~, then we say task B depends on
   task A. We can use Makefile, a config file, to express this.

#+BEGIN_SRC make
  b.output : a.output
  [TAB]echo "Generate b.output" 
  [TAB]cat a.output > b.output
  a.output :
  [TAB]echo "Generate a.output"
  [TAB]touch a.output
#+END_SRC
  You can save the lines above into a file like /Makefile/. Then run
  ~make~. The system will generate both /a.output/ and /b.output/, if
  no such files exist before.
  
  1. By default, make will search /Makefile/ or /makefile/ under
     current path. You can use ~make -f /your_make_file/~ to let run
     whatever Makefile you named.
  2. If /a.output/ exists, then ~make~ will run the rule under
     ~b.output : a.output~, i.e., ~echo "Generate b.output"~ and
     ~cat a.output > b.output~
** Snakemake
*** Why we need it
  - I want to submit 1,000 jobs.
  - Some of them are failed, I need to rerun them.
  - I have a pipeline, which means jobs have dependencies
*** Jobs manager:
  - handle jobs' dependencies
  - automatically run the pipeline from where it failed
  - if some intermedia files / scripts are updated, then automatically
  update all the later rules depend on them.
*** Snakemake = Snake[Python] + make[GNU make]
**** [[https://en.wikipedia.org/wiki/Make_(software)][make]]: dependency-tracking build utilities, written in 1976
    - Still widely used now, especially [[https://www.gnu.org/software/make/manual/make.html#Introduction][GNU make]]
    - Drawback:
      - Lack of configuration file support, like *yaml*, *json*.
      - Lack of support for jobs on HPC
    - Snakemake may die in the future, but make should be still alive.
**** Snakemake:
    - written in Python, which makes it simple to use
    - support config files like *yaml*, *json*.
    - support HPC: both PBS and Slurm
**** How it looks like:
 #+BEGIN_SRC snakemake
    ## optional config file
    configfile: "config.yaml"
    content = "say hi"
    samples = ["a", "b"]
    ## all the output files you want to have
    rule all:
        input:
           expand("flag/pre_{s}.done", s = samples)
           expand("flag/first_{s}.done", s = samples)

    ## then set up the rules about how to generate them
    rule pre:
        output:
           # s will be infered based on rule all output
           # here it will be a or b.
           # snakemake will run s=a and s=b in parallel if possible
           # touch will be automatically  generate the flag file
           # once the rule is done.
           touch("flag/pre_{s}.done")
        log:
           "log/{s}.log"
        shell:
           """
           # wildcards.s to get the a / b
           echo "pre:" {content} {wildcards.s} 2> {log}
           """
   rule first:
       # snakemake will know that it depends on the output of pre
       # then the rule will run after pre
       input:
           "flag/pre_{s}.done"
       output:
           touch("flag/first_{s}.done")
       log:
           "log/{s}.log"
       shell:
           """
           echo "first:" {content} {wildcards.s} 2> {log}
           """
 #+END_SRC
 - Then save the above into a file named *demo.snakefile*.
 - =snakemake --snakefile demo.snakefile= to run the snakemake.
**** Summary
  - *snakefile*
    - just python syntax + snakemake key words, such as *config*,
      *rule*, *expand*, *wildcards* and so on.
    - [OPTION but good in practice] *config.yaml* to claim variables
  - The *input* in *rule all* is used to claim all the final outputs
  - *input* and *output* of *rules* to organize the depencies of tasks.
  - *wildcards*
    - inferred based on file names
    - the key mechanism to run multiple jobs in parallel

  

   
